# yaml-language: $schema=./node_modules/envio/evm.schema.json
name: stablerent-subscription-indexer
description: StableRent - Crypto Subscription Manager with Envio Integration

contracts:
  - name: StableRentSubscription
    abi: ./artifacts/contracts/StableRentSubscription.sol/StableRentSubscription.json
    events:
      - event: "SubscriptionCreated(uint256 subscriptionId, address subscriber, uint256 serviceProviderId, uint256 amount, uint256 interval, uint256 nextPaymentDue, uint256 endDate, uint256 maxPayments, string serviceName, uint8 paymentType, uint8 providerType, address recipientAddress, string recipientCurrency, uint256 processorFee, address processorFeeAddress, string processorFeeCurrency, uint256 processorFeeID, uint256 timestamp)"
      - event: "PaymentProcessed(uint256 subscriptionId, address subscriber, uint256 amount, uint256 processorFee, address processorFeeAddress, uint256 paymentCount, uint256 timestamp, uint256 nextPaymentDue)"
      - event: "PaymentFailed(uint256 subscriptionId, address subscriber, uint256 amount, uint256 timestamp, string reason, uint256 failedCount)"
      - event: "SubscriptionCancelled(uint256 subscriptionId, address subscriber, uint256 timestamp, string reason)"

networks:
  - id: 11155111 # ethereum-sepolia
    start_block: 9470537
    contracts:
      - name: StableRentSubscription
        address: 0x278dD89e80B01772affcC8cAEa6e45fFF8Ae3339